name = "atomic-arcade"
main = "src/index.ts"
compatibility_date = "2025-05-08"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public/"
binding = "ASSETS"

[vars]
TRIFROST_NAME="atomic-arcade"
TRIFROST_VERSION="0.1.0"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
invocation_logs = false
